version: '3.8'

services:
  s5js-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: s5js-prod
    image: s5js-server:prod
    ports:
      - "5522:5522"
    environment:
      - S5_MODE=${S5_MODE:-real}  # Default to real mode
      - PORT=5522
      - NODE_ENV=production
      - S5_SEED_FILE=/home/nodejs/.s5-seed  
    volumes:
      # Mount seed file if it exists
      - ${HOME}/.s5-seed:/home/nodejs/.s5-seed:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5522/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    mem_limit: 512m
    memswap_limit: 1g
    cpus: 1.0
    networks:
      - s5-network

networks:
  s5-network:
    driver: bridge